routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('/reset', function(){
    session()->flush();

    return redirect('/');
});

Auth::routes();

Route::post('/password/phone', 'Auth\ForgotPasswordController@phone')->name('password.phone');
Route::get('/password/change', 'Auth\ResetPasswordController@change')->name('password.change');
Route::post('/password/update', 'Auth\ResetPasswordController@update')->name('password.update');

Route::get('/register/success', 'Auth\RegisterController@success');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/restaurants/request', 'RestaurantRequestController@store');
Route::post('/restaurants/request/bulk', 'RestaurantRequestController@bulk');
Route::get('/restaurants/explore', 'RestaurantsController@index');
Route::get('/restaurants/{city}/{restaurantSlug}', 'RestaurantsController@show');

Route::post('/cart/add', 'CartController@store');
Route::post('/cart/custom/add', 'CartController@storeCustom');
Route::post('/cart/remove/{itemId}', 'CartController@destroy');
Route::post('/cart/update/{itemId}', 'CartController@update');
Route::get('/cart', 'CartController@index');

Route::get('/search', 'SearchController@index');

Route::get('/checkout', 'CheckoutController@index');

Route::post('/orders', 'OrdersController@store');
Route::get('/orders/{order}', 'OrdersController@show');
Route::get('/orders/{order}/invoice', 'OrdersController@invoice');
Route::get('/orders/{order}/confirm', 'OrdersController@confirm');
Route::get('/orders/{order}/ready', 'OrdersController@ready');
Route::get('/orders/{order}/picked', 'OrdersController@picked');
Route::get('/orders/{order}/delivered', 'OrdersController@delivered');
Route::get('/orders/{order}/cancel', 'OrdersController@cancel');
Route::get('/thankyou', 'ThankyouController@index');
Route::get('/pay', 'PaymentsController@pay');

Route::post('/payments/response/', 'PaymentsController@response');
Route::post('/payments/cancel/', 'PaymentsController@cancel');

Route::post('/addresses', 'AddressController@store');
Route::get('/addresses/{address}/delete', 'AddressController@destroy');
Route::post('/addresses/{address}/update', 'AddressController@update');

Route::post('user/location', 'Api\UserLocationController@store');

Route::get('/my-account', 'AccountController@profile');
Route::get('/my-account/orders', 'AccountController@orders');
Route::get('/my-account/offers', 'AccountController@offers');
Route::get('/my-account/payments', 'AccountController@payments');
Route::get('/my-account/bookmarks', 'AccountController@bookmarks');
Route::get('/my-account/addresses', 'AccountController@addresses');

Route::post('/account/update', 'AccountController@updateProfile');
Route::post('/account/update/password', 'AccountController@updatePassword');
Route::post('/account/phone/update', 'AccountController@updatePhone');

Route::get('/bookmarks/{restaurant}', 'BookmarkController@store');
Route::get('/bookmarks/{restaurant}/remove', 'BookmarkController@destroy');

Route::get('/coupons', 'CouponsController@index');
Route::post('/coupons/apply', 'CouponsController@apply');
Route::get('/coupons/remove', 'CouponsController@destroy');
Route::post('/coupons/apply/foodoor', 'CouponsController@applyFoodoor');

Route::post('/cart/clear', 'CartController@clear');


Route::get('/company/about', 'CompanyController@about');
Route::get('/company/contact', 'CompanyController@contact');
Route::get('/company/careers', 'CompanyController@careers');
Route::get('/company/team', 'CompanyController@team');
Route::get('/company/terms', 'CompanyController@terms');
Route::get('/company/privacy-policy', 'CompanyController@privacy');

Route::post('/contact', 'ContactController@store');

app/Models/Order.php
<?php

namespace App\Models;

use App\User;
use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'orders';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $guarded = [];
    // protected $hidden = [];
    // protected $dates = [];

   public function restaurant()
   {
        return $this->belongsTo(Restaurant::class);
   }

    public function customer()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getBookingDateAttribute()
    {
        return $this->created_at->format('d/m/Y');
    }

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function getStatusTextAttribute()
    {
        $statuses = ['Order Placed', 'Confirmed by Restaurant', 'Order Ready' , 'Order Picked', 'Order Delivered'];
        return $statuses[$this->status];
    }

    public function getCancelledByNameAttribute()
    {
        return $this->cancelled_by == 0 ? 'Customer' : 'Restaurant';
    }

    public function getItemsCountAttribute()
    {
        return count($this->items);
    }

    public function getPaymentBadgeAttribute()
    {
        if($this->payment_mode == 0)
        {
            if($this->status < 4) {
                $status = 'Payment Pending';
                $color = 'danger';
            } else {
                $status = 'Payment Received';
                $color = 'success';
            }
        } else {
            if($this->status > -1) {
               $status = 'Payment Received';
                $color = 'success';
            }
        }

        return '<small><span class="badge badge-' . $color . '">' . $status . '</span></small>';
    }

    public function getStatusBadgeAttribute()
    {
        $statuses = ['Awaiting Confirmation', 'Confirmed', 'Ready', 'Picked', 'Delivered'];
        $colors = ['secondary', 'primary', 'info', 'warning', 'success'];
        return '<small><span class="badge badge-' . $colors[$this->status] . '">' . $statuses[$this->status] . '</span></small>';
    }
    public function getAmountEarnedAttribute()
    {
        return $this->subtotal - $this->commission_earned;
    }

    public function confirmOrder($crud = false)
    {
        if($this->status < 1)
        {
           return '<a class="btn btn-xs btn-success" href="/orders/'. $this->id . '/confirm" data-toggle="tooltip" title="Confirm Order"><i class="fa fa-check"></i> Confirm Order</a>';
        } elseif($this->status == 1) {

                 return '<a class="btn btn-xs btn-info" href="/orders/'. $this->id . '/ready" data-toggle="tooltip" title="Order Ready" ><i class="fa fa-check"></i> Order Ready</a>';
        } elseif($this->status == 2) {

                 return '<a class="btn btn-xs btn-info" href="/orders/'. $this->id . '/picked" data-toggle="tooltip" title="Order Picked" ><i class="fa fa-check"></i> Order Picked</a>';
        } elseif($this->status == 3) {

                 return '<a class="btn btn-xs btn-success" href="/orders/'. $this->id . '/delivered" data-toggle="tooltip" title="Order Delivered" ><i class="fa fa-check"></i> Order Delivered</a>';
        } else {
             return '<a class="btn btn-xs btn-success" href="#" data-toggle="tooltip" title="Order Delivered" disabled><i class="fa fa-check"></i> Order Closed</a>';
        }

    }

     public function cancelOrder($crud = false)
    {
           return
           '<a class="btn btn-xs btn-danger" href="/orders/'. $this->id . '/cancel" data-toggle="tooltip"  title="Cancel Order"><i class="fa fa-file-text"></i> Cancel</a>';
    }


    public function invoice($crud = false)
    {
           return
           '<a class="btn btn-xs btn-primary" href="/orders/'. $this->id . '/invoice" data-toggle="tooltip" target="_blank" title="Download Invoice"><i class="fa fa-file-text"></i> Invoice</a>';
    }




    public function addCustomerDetails($addressId)
    {
        $address = Address::findOrFail($addressId);
        $this->user_id = auth()->id();
        $this->customer_name = auth()->user()->name;
        $this->customer_phone = auth()->user()->phone;
        $this->customer_email = auth()->user()->email;
        $this->delivery_location = $address->location;
        $this->delivery_latitude = $address->latitude;
        $this->delivery_longitude = $address->longitude;
        $this->delivery_door_no = $address->door_no;
        $this->delivery_road_name = $address->road_name;
        $this->delivery_landmark = $address->landmark;
    }

    public function addRestaurantDetails($restaurant)
    {

        $this->restaurant_id = $restaurant->id;
        $this->restaurant_name = $restaurant->name;
        $this->restaurant_location = $restaurant->location;
        $this->restaurant_latitude = $restaurant->latitude;
        $this->restaurant_longitude = $restaurant->longitude;
        $this->restaurant_area = $restaurant->area;
    }

    public function addBillingDetails($bill)
    {
        $this->subtotal = $bill['subTotal'];
        $this->tax = $bill['gst'];
        $this->delivery_charges = $bill['deliveryCharges'];
        $this->total = ceil(round($bill['total'], 2));
        $this->discount = $bill['discount'] != null ? $bill['discount']  : 0;
        $this->commission_earned = $this->subtotal * ($this->restaurant->commission/100);
    }

    public function storeItems($items)
    {
        foreach ($items as $key => $item) {
            $this->items()->create(['menu_item_id' => $item->attributes->item_id, 'name' => $item->name,
                                'price' => $item->price, 'qty' => $item->quantity, 'total' => $item->price * $item->quantity,
                                'customs' => getCustomsString($item)]);
        }
    }


    public function getStatusIconAttribute()
    {
         $statuses = ['Awaiting Confirmation', 'Confirmed', 'Ready', 'Picked', 'Delivered'];
         $icons = ['clock', 'check-circle', 'shopping-bag', 'motorcycle', 'check'];
         return $icons[$this->status];
    }

    public function getStatusDescAttribute()
    {
        $statuses = ['Awaiting Confirmation', 'Confirmed', 'Ready', 'Picked', 'Delivered'];
        $colors = ['secondary', 'primary', 'info', 'warning', 'success'];
        return $statuses[$this->status];
    }
}

resources/views/admin/dashboard.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
      <h1>
        {{ trans('backpack::base.dashboard') }}<small>{{ trans('backpack::base.first_page_you_see') }}</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="{{ backpack_url() }}">{{ config('backpack.base.project_name') }}</a></li>
        <li class="active">{{ trans('backpack::base.dashboard') }}</li>
      </ol>
    </section>
@endsection


@section('content')
     <div class="row">



          <div class="col-md-6">
           <div class="box">
            <div class="box-header">
              <h3 class="box-title">Monthly Sales</h3>


            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>Month</th>
                  <th>Sales (Rs.)</th>
                  <th>Profit Earned (Rs.)</th>
                </tr>
                @foreach($earnings as $index => $earning)
                <tr>
                  <td>{{ getMonth($earning->month) }}</td>
                  <td><span class="label label-warning">Rs. {{ $earning->sales }}</span></td>
                  <td><span class="label label-success">Rs. {{ $earning->profits }}</span></td>
                </tr>
                @endforeach
              </tbody></table>
            </div>
            <!-- /.box-body -->


        </div>
          <!-- /.box -->
          </div>




          <div class="col-md-6">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Recent Customers</h3>


            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>Order ID</th>
                  <th>Customer Name</th>
                  <th>Customer Phone</th>
                  <th>Last Order</th>
                </tr>
                @foreach($recentOrders as $index => $order)
                <tr>
                  <td>{{ $order->id }}</td>
                  <td>{{ $order->customer_name }}</td>
                  <td>{{ $order->customer_phone }}</td>
                  <td><span class="label label-primary">{{ $order->booking_date }}</span></td>
                </tr>
                @endforeach
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>

        </div>
        <!-- /.col (RIGHT) -->
      </div>

      <div class="row">
        <div class="col-md-6">
           <div class="box">
            <div class="box-header">
              <h3 class="box-title">Earnings By Restaurant</h3>


            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>Restaurant</th>
                  <th>Sales (Rs.)</th>
                  <th>Profit Earned (Rs.)</th>
                </tr>
                @foreach($restaurantEarnings as $index => $earning)
                <tr>
                  <td>{{ getRestaurantName($earning->restaurant_id) }}</td>
                  <td><span class="label label-warning">Rs. {{ $earning->sales }}</span></td>
                  <td><span class="label label-success">Rs. {{ $earning->profits }}</span></td>
                </tr>
                @endforeach
              </tbody></table>
            </div>
            <!-- /.box-body -->


        </div>
          <!-- /.box -->
          </div>
      </div>


      <section class="content-header" style="margin-left: -14px;">
      <h1>
       Charts
      </h1>

    </section>
@endsection