routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('/reset', function(){
    session()->flush();

    return redirect('/');
});

Auth::routes();

Route::post('/password/phone', 'Auth\ForgotPasswordController@phone')->name('password.phone');
Route::get('/password/change', 'Auth\ResetPasswordController@change')->name('password.change');
Route::post('/password/update', 'Auth\ResetPasswordController@update')->name('password.update');

Route::get('/register/success', 'Auth\RegisterController@success');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/restaurants/request', 'RestaurantRequestController@store');
Route::post('/restaurants/request/bulk', 'RestaurantRequestController@bulk');
Route::get('/restaurants/explore', 'RestaurantsController@index');
Route::get('/restaurants/{city}/{restaurantSlug}', 'RestaurantsController@show');

Route::post('/cart/add', 'CartController@store');
Route::post('/cart/custom/add', 'CartController@storeCustom');
Route::post('/cart/remove/{itemId}', 'CartController@destroy');
Route::post('/cart/update/{itemId}', 'CartController@update');
Route::get('/cart', 'CartController@index');

Route::get('/search', 'SearchController@index');

Route::get('/checkout', 'CheckoutController@index');

Route::post('/orders', 'OrdersController@store');
Route::get('/orders/{order}', 'OrdersController@show');
Route::get('/orders/{order}/invoice', 'OrdersController@invoice');
Route::get('/orders/{order}/confirm', 'OrdersController@confirm');
Route::get('/orders/{order}/ready', 'OrdersController@ready');
Route::get('/orders/{order}/picked', 'OrdersController@picked');
Route::get('/orders/{order}/delivered', 'OrdersController@delivered');
Route::get('/orders/{order}/cancel', 'OrdersController@cancel');
Route::get('/thankyou', 'ThankyouController@index');
Route::get('/pay', 'PaymentsController@pay');

Route::post('/payments/response/', 'PaymentsController@response');
Route::post('/payments/cancel/', 'PaymentsController@cancel');

Route::post('/addresses', 'AddressController@store');
Route::get('/addresses/{address}/delete', 'AddressController@destroy');
Route::post('/addresses/{address}/update', 'AddressController@update');

Route::post('user/location', 'Api\UserLocationController@store');

Route::get('/my-account', 'AccountController@profile');
Route::get('/my-account/orders', 'AccountController@orders');
Route::get('/my-account/offers', 'AccountController@offers');
Route::get('/my-account/payments', 'AccountController@payments');
Route::get('/my-account/bookmarks', 'AccountController@bookmarks');
Route::get('/my-account/addresses', 'AccountController@addresses');

Route::post('/account/update', 'AccountController@updateProfile');
Route::post('/account/update/password', 'AccountController@updatePassword');
Route::post('/account/phone/update', 'AccountController@updatePhone');

Route::get('/bookmarks/{restaurant}', 'BookmarkController@store');
Route::get('/bookmarks/{restaurant}/remove', 'BookmarkController@destroy');

Route::get('/coupons', 'CouponsController@index');
Route::post('/coupons/apply', 'CouponsController@apply');
Route::get('/coupons/remove', 'CouponsController@destroy');
Route::post('/coupons/apply/foodoor', 'CouponsController@applyFoodoor');

Route::post('/cart/clear', 'CartController@clear');


Route::get('/company/about', 'CompanyController@about');
Route::get('/company/contact', 'CompanyController@contact');
Route::get('/company/careers', 'CompanyController@careers');
Route::get('/company/team', 'CompanyController@team');
Route::get('/company/terms', 'CompanyController@terms');
Route::get('/company/privacy-policy', 'CompanyController@privacy');

Route::post('/contact', 'ContactController@store');

app/Models/Address.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Address extends Model
{
    protected $fillable = ['user_id', 'location', 'latitude', 'longitude', 'door_no', 'road_name', 'landmark', 'type'];

    public function getTypeStringAttribute()
    {
        $types = ['Home', 'Office', 'Other'];

        return $types[$this->type];
    }
}

app/Http/Controllers/CheckoutController.php
<?php

namespace App\Http\Controllers;

use App\Models\MenuItem;
use Illuminate\Http\Request;

class CheckoutController extends Controller
{
    public function index()
    {

        $items = \Cart::getContent();
        if(count($items))
        {
            $menuItem = MenuItem::findOrFail($items->first()->attributes->item_id);
            $restaurant = $menuItem->restaurant;

            $bill['subTotal'] = \Cart::getSubTotal();
            $bill['gst'] = round($bill['subTotal'] * (5/100), 2);
            $bill['deliveryCharges'] = 30;
            $condition = \Cart::getCondition('discount');
            if(isset($condition))
            {
              $bill['discount'] = $condition->getCalculatedValue(\Cart::getTotal());
            } else {
                 $bill['discount'] = null;
            }
            $bill['total'] = \Cart::getTotal() + $bill['gst'] + $bill['deliveryCharges'];

            return view('checkout.index', compact('restaurant', 'bill'));
        } else {
            return view('checkout.none');
        }

    }
}

resources/views/checkout/index.blade.php
@extends('layouts.app')



@section('content')

    <div class="bg-light checkout" style="min-height: 90vh;">
        <div class="container py-5 py-res-0">
            <div class="row">
                <div class="col-md-8">

                    <div v-if="loggedIn" class="card address-card card-shadow">
                      <div class="card-body">
                        <h4 class="font-weight-bold mb-4">Delivery Address</h4>
                        <el-alert
                                  v-if="checkoutError"
                                  :title="checkoutErrorMessage"
                                  type="error"
                                  class="mb-2 mt-2"
                                  show-icon>
                                </el-alert>

                        @if(auth()->check() && auth()->user()->addresses()->count())
                          @include('checkout.partials._addresscarousel')
                        @endif
                       <div class="row address-col">
                        @if(auth()->check())

                        @foreach(auth()->user()->addresses as $address)
                          <div class="col-md-6">
                            <div class="card address">
                                <div class="card-body pt-1">
                                    <span class="badge badge-warning">{{ $address->type_string }}</span>
                                    <h6 class="font-weight-bold mt-2">{{ str_limit($address->location, 70) }}</h6>
                                    <p><b>Door No.: </b> {{ $address->door_no }} | {{ $address->road_name }}
                                    <br><b>Landmark : </b> {{ $address->landmark }}</p>
                                    <p ><a data-toggle="modal" href="#editAddress-{{$address->id}}">Edit</a> | <a href="/addresses/{{$address->id}}/delete" onclick="return confirm('Are you sure, you want to delete the address');">Delete</a></p>



                                     <el-radio @change="checkoutError = false"  v-model="checkout.address_id" label="{{ $address->id }}" border>Deliver Here</el-radio>
                                    </button>
                                </div>
                            </div>
                          </div>
                        @endforeach
                        @endif
                        </div>
                        <button data-toggle="modal" data-target="#addressModal" class="btn btn-primary mt-4">Add New Address</button>
                        @include('checkout.partials._addaddress')
                      </div>
                    </div>
                    <div v-else class="card account-card  card-shadow">
                        <div class="card-body">
                            <h4 class="font-weight-bold mb-4">Account</h4>
                            <div class="login-container" style="width: 60%;">
                             <login-register @loggedin="changeLoginStatus"></login-register>
                            </div>
                        </div>
                    </div>

                    <div v-if="loggedIn" class="card payment-card card-shadow">
                        <div class="card-body">
                            <h4 class="font-weight-bold mb-4">Payment</h4>
                            <div>
                              <input type="hidden" id="address" name="address" v-model="checkout.address_id">

                              <div>
                                <el-radio v-model="checkout.payment_mode" :label="0" border>COD</el-radio>
                                <el-radio v-model="checkout.payment_mode" :label="1" border>Pay Online</el-radio>
                              </div>

                              <div class="mt-4 place-order-section">
                                <el-input type="number" class="alt_mobile_input" v-model="checkout.delivery_alt_no" placeholder="Alternate Mobile Number (optional)"></el-input>
                                <el-button class="place-order-btn" @click="placeOrder()" type="success" :loading="placingOrder">Place Order</el-button>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 mb-4">
                    <div class="card cart  card-shadow">
                        <div class="card-body">
                        <div class="d-flex">
                            <img src="{{ isset($restaurant->logo) ? url($restaurant->logo) : 'http://via.placeholder.com/90x90' }}" style="width: 50px;height: 50px;" alt="restaurants feature">
                            <div class="ml-2">
                                <h5 class="restaurant-name"><a class="text-dark" href="/restaurants/{{ str_slug($restaurant->city->name) }}/{{$restaurant->slug}}">{{ $restaurant->name }}</a></h5>
                                <p class="restaurant-area">{{ $restaurant->area }}</p>
                            </div>
                        </div>

                        <div v-if="itemsCount == 0" class="cart-empty-view">
                            <p>There are no items in your cart</p>
                        </div>

                        <a v-else href="#cartModal" data-toggle="modal" class="view-cart" style="display: none;">View Detailed Cart</a>

                        <div v-if="itemsCount > 0"  class="cart-items my-3">
                            <div class="">
                            <div v-for="item in cartItems" class="item d-flex justify-content-between align-items-center">

                                    <div style="flex: 1">
                                        <h4 class="name">
                                                 <img v-if="item.is_veg" class="veg-indicator" src="/img/veg.png" style="width: 15px;height: 15px;margin-top: -4.5px;" alt="restaurant">

                                                <img v-else class="veg-indicator" src="/img/nonveg.png" style="width: 15px;height: 15px;margin-top:-4.5px;" alt="restaurant">

                                               @{{ item.name }}</h4>
                                        <p class="price">₹ @{{ item.price * item.quantity }}</p>
                                    </div>

                                    <input type="number" class="number-input" :value="item.quantity" :id="item.id+'-qty'" @change="updateCartItem(item.id, item.attributes.item_id)" >
                                    <!-- <spinner inline controls size="small" :value="item.quantity" @change="(newValue, oldValue, item) => {}"></spinner> -->


                            </div>
                            </div>
                        </div>
                        <div class="coupons-button">
                            <a v-if="bill.discount == null" href="#couponsModal" data-toggle="modal" class="btn btn-secondary">Apply Coupon</a>
                            <buttom @click="removeCoupon()" v-else class="btn btn-danger"><i class="fas fa-trash"></i> Remove Coupon</button>
                        </div>
                         <div class="suggestions">
                            <input class="form-control" placeholder="Any suggestions for restaurant?" name="suggestions" v-model="checkout.suggestions" id="suggestions" />
                        </div>
                        <div class="cart-bill">
                            <table class="table table-borderless">
                                 <tbody>
                                    <tr>
                                      <td>Subtotal</td>
                                      <td class="amount">₹ @{{ bill.subTotal }}</td>
                                    </tr>
                                    <tr>
                                      <td>GST</td>
                                      <td class="amount">₹ @{{ bill.gst }}</td>
                                    </tr>
                                    <tr class="delivery">
                                      <td>Delivery Charges</td>
                                      <td class="amount">₹ @{{ bill.deliveryCharges }}</td>
                                    </tr>
                                     <tr v-if="bill.discount != null" class="discount">
                                      <td>Discount</td>
                                      <td class="amount">- ₹ @{{ bill.discount }}</td>
                                    </tr>
                                     <tr class="total">
                                      <td>To Pay</td>
                                      <td class="amount">₹ @{{ bill.total }}</td>
                                    </tr>
                                 </tbody>
                            </table>
                        </div>
                       </div>

                    </div>
                </div>
            </div>

             <el-button class="confirm-order" @click="placeOrder()" type="success" :loading="placingOrder"  style="display: none;">
            Place Order
        </el-button>
        </div>
    </div>



    <div class="modal fade" id="cartModal" style="z-index: 10000000000;" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Your Cart <br> <small class="count text-muted">@{{ cartItems.length }} ITEMS</small></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="cart">

                        <div v-if="itemsCount == 0" class="cart-empty-view">
                            <p>There are no items in your cart</p>
                        </div>

                        <div v-else>
                        <div  class="card cart-items my-3">
                            <div class="card-body">
                            <div v-for="item in cartItems" class="item d-flex justify-content-between align-items-center">

                                    <div style="flex: 1">
                                        <h4 class="name">
                                                 <img v-if="item.is_veg" class="veg-indicator" src="/img/veg.png" style="width: 15px;height: 15px;margin-top: -4.5px;" alt="restaurant">

                                                <img v-else class="veg-indicator" src="/img/nonveg.png" style="width: 15px;height: 15px;margin-top:-4.5px;" alt="restaurant">

                                               @{{ item.name }}</h4>
                                        <p class="price">₹ @{{ item.price * item.quantity }}</p>
                                    </div>

                                    <input type="number" class="number-input" :value="item.quantity" :id="item.id+'-qty-modal'" @change="updateModalCartItem(item.id, item.attributes.item_id)" >
                                    <!-- <spinner inline controls size="small" :value="item.quantity" @change="(newValue, oldValue, item) => {}"></spinner> -->


                            </div>
                            </div>
                        </div>

                        </div>

                    </div>
      </div>

    </div>
  </div>
</div>

@include('checkout.partials._coupons')

@if(auth()->check())
@foreach(auth()->user()->addresses as $address)
   @include('checkout.partials._editaddress')
@endforeach
@endif

@endsection


@section('scripts')



@endsection

resources/views/checkout/none.blade.php
@extends('layouts.app')

@section('content')

    <div style="height: 80vh;" class="d-flex align-items-center justify-content-center">
        <div class="text-center">
            <img src="/img/empty.png" style="width: 150px;height: 100%;display: block;margin: 0 auto;margin-bottom: 15px;" alt="restaurant" />
            <h3 class="font-weight-bold" style="letter-spacing: 2px;">Your cart is empty!</h3>
            <p class="text-muted" style="font-size: 19px;letter-spacing: 1px;">Explore our restaurants and add some items in your cart</p>
            <a href="/restaurants/explore" class="btn btn-primary">Explore Restaurants</a>
        </div>
    </div>

@endsection

resources/views/checkout/success.blade.php
@extends('layouts.app')


@section('tracking')

    <!-- Event snippet for Order Completion (AdWords) conversion page -->
<script>
  gtag('event', 'conversion', {
      'send_to': 'AW-792677172/wQ-aCIzjpIsBELSW_fkC',
      'transaction_id': ''
  });
</script>

@endsection


@section('content')

<div style="height: 80vh;" class="d-flex align-items-center justify-content-center">
    <div class="text-center">
        <img src="/img/success.png" style="width: 150px;height: 100%;display: block;margin: 0 auto;margin-bottom: 15px;" alt="restaurant" />
        <h3 class="font-weight-bold" style="letter-spacing: 2px;">Thank you placing an order!</h3>
        <p class="text-muted"  style="font-size: 19px;letter-spacing: 1px;">Your order will shortly arrive to you. Click the button below to track your order.</p>
        <a href="/orders/{{$order->id}}" class="btn btn-primary">Track My Order</a>
    </div>
</div>

@endsection