routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('/reset', function(){
    session()->flush();

    return redirect('/');
});

Auth::routes();

Route::post('/password/phone', 'Auth\ForgotPasswordController@phone')->name('password.phone');
Route::get('/password/change', 'Auth\ResetPasswordController@change')->name('password.change');
Route::post('/password/update', 'Auth\ResetPasswordController@update')->name('password.update');

Route::get('/register/success', 'Auth\RegisterController@success');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/restaurants/request', 'RestaurantRequestController@store');
Route::post('/restaurants/request/bulk', 'RestaurantRequestController@bulk');
Route::get('/restaurants/explore', 'RestaurantsController@index');
Route::get('/restaurants/{city}/{restaurantSlug}', 'RestaurantsController@show');

Route::post('/cart/add', 'CartController@store');
Route::post('/cart/custom/add', 'CartController@storeCustom');
Route::post('/cart/remove/{itemId}', 'CartController@destroy');
Route::post('/cart/update/{itemId}', 'CartController@update');
Route::get('/cart', 'CartController@index');

Route::get('/search', 'SearchController@index');

Route::get('/checkout', 'CheckoutController@index');

Route::post('/orders', 'OrdersController@store');
Route::get('/orders/{order}', 'OrdersController@show');
Route::get('/orders/{order}/invoice', 'OrdersController@invoice');
Route::get('/orders/{order}/confirm', 'OrdersController@confirm');
Route::get('/orders/{order}/ready', 'OrdersController@ready');
Route::get('/orders/{order}/picked', 'OrdersController@picked');
Route::get('/orders/{order}/delivered', 'OrdersController@delivered');
Route::get('/orders/{order}/cancel', 'OrdersController@cancel');
Route::get('/thankyou', 'ThankyouController@index');
Route::get('/pay', 'PaymentsController@pay');

Route::post('/payments/response/', 'PaymentsController@response');
Route::post('/payments/cancel/', 'PaymentsController@cancel');

Route::post('/addresses', 'AddressController@store');
Route::get('/addresses/{address}/delete', 'AddressController@destroy');
Route::post('/addresses/{address}/update', 'AddressController@update');

Route::post('user/location', 'Api\UserLocationController@store');

Route::get('/my-account', 'AccountController@profile');
Route::get('/my-account/orders', 'AccountController@orders');
Route::get('/my-account/offers', 'AccountController@offers');
Route::get('/my-account/payments', 'AccountController@payments');
Route::get('/my-account/bookmarks', 'AccountController@bookmarks');
Route::get('/my-account/addresses', 'AccountController@addresses');

Route::post('/account/update', 'AccountController@updateProfile');
Route::post('/account/update/password', 'AccountController@updatePassword');
Route::post('/account/phone/update', 'AccountController@updatePhone');

Route::get('/bookmarks/{restaurant}', 'BookmarkController@store');
Route::get('/bookmarks/{restaurant}/remove', 'BookmarkController@destroy');

Route::get('/coupons', 'CouponsController@index');
Route::post('/coupons/apply', 'CouponsController@apply');
Route::get('/coupons/remove', 'CouponsController@destroy');
Route::post('/coupons/apply/foodoor', 'CouponsController@applyFoodoor');

Route::post('/cart/clear', 'CartController@clear');


Route::get('/company/about', 'CompanyController@about');
Route::get('/company/contact', 'CompanyController@contact');
Route::get('/company/careers', 'CompanyController@careers');
Route::get('/company/team', 'CompanyController@team');
Route::get('/company/terms', 'CompanyController@terms');
Route::get('/company/privacy-policy', 'CompanyController@privacy');

Route::post('/contact', 'ContactController@store');

app/Models/Restaurant.php
<?php

namespace App\Models;

use Backpack\CRUD\CrudTrait;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;

class Restaurant extends Model
{
    use CrudTrait;

        const DISTANCE_UNIT_KILOMETERS = 111.045;
const DISTANCE_UNIT_MILES      = 69.0;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'restaurants';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $fillable = [ 'name', 'slug', 'area',  'location', 'logo', 'contact_name', 'contact_phone', 'contact_email', 'username', 'password', 'website', 'city_id', 'timings', 'bank_name', 'bank_ifsc', 'bank_acc_no', 'bank_acc_name', 'bank_acc_type',  'promo_text', 'discount_type', 'discount', 'valid_from', 'valid_through', 'min_order', 'latitude', 'longitude', 'cost_for_two', 'is_pure_veg',   'commission', 'days_open', 'gst_applicable', 'delivery_time', 'is_featured', 'days'];
    // protected $hidden = [];
    // protected $dates = [];

    protected $casts = [
        'timings' => 'json',
        'days_open' => 'array'
    ];

   public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function getCityNameAttribute()
    {
        return $this->city->name;
    }

    public function getIsOpenAttribute()
    {

        if($this->all_day)
        {
            return true;
        }



        $isOpen = false;
        $now = date("h:i A");
        foreach($this->timings as $timing)
        {

            if(array_key_exists('open_time', $timing) && array_key_exists('close_time', $timing))
            {
                $stime = $timing['open_time'];
                $etime = $timing['close_time'];
                $isOpen = strtotime($now) < strtotime($etime) && strtotime($now) > strtotime($stime);
            }




            if($isOpen)
            {
                break;
            }
        }

        return $isOpen;
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function getOrdersServedAttribute()
    {
        return $this->orders()->count();
    }
    public function items()
    {
        return $this->hasMany(MenuItem::class);
    }

    public function getIsBookmarkedAttribute()
    {
        return auth()->user()->bookmarks->contains($this);
    }

    public function featuredItems()
    {
        return $this->hasMany(MenuItem::class)->where('is_featured', 1);
    }

    public function getCuisineMenuAttribute()
    {
        $cuisineIds = array_keys($this->items->groupBy('cuisine_id')->toArray());
        $cuisines = [];

        foreach ($cuisineIds as $key => $cuisine) {
            $cuisineModel = Cuisine::findOrFail($cuisine);

             $cuisines[] = $cuisineModel;
        }

        $cuisineMenu = [];

         foreach ($cuisines as $key => $cuisine) {
            if($cuisine->parent_id == 0 || $cuisine->parent_id == null)
            {
              $cuisineMenu[] = $cuisine;
            } else {
              $cuisineMenu[] = $cuisine->parent;
            }
        }


         $cuisineMenu = array_unique($cuisineMenu);

         $cuisines = array_unique($cuisines);

         usort($cuisines, array($this, "cmp"));

         usort($cuisineMenu, array($this, "cmp"));

         return $cuisineMenu;
    }

    public function cmp($a, $b)
    {
        return strcmp($a->name, $b->name);
    }

    public function cuisines()
    {
        return $this->belongsToMany(Cuisine::class);
    }

    public function getOpenIndicatorAttribute()
    {
        return $this->is_open ? 'success' : 'danger';
    }
    public function getOpenStatusAttribute()
    {
        return $this->is_open ? 'Open Now' : 'Closed';
    }



    public function getCuisinesAvailableAttribute()
    {
        return implode(', ', $this->cuisines()->limit(3)->pluck('name')->toArray());
    }

    public function manageItems($crud = false)
    {

        return '<a class="btn btn-xs btn-success" href="/admin/menu-items?restaurant=' . $this->id . '" data-toggle="tooltip" title="Manage Menu"><i class="fa fa-list-ul"></i> Menu Items</a>';

    }

    public function ordersHistory()
    {
        return '<a class="btn btn-xs btn-primary" href="/admin/orders?restaurant=' . $this->id . '" data-toggle="tooltip" title="Manage Orders"><i class="fa fa-file-text"></i> Orders History</a>';
    }

    /* public function items()
    {
        return $this->hasMany(Item::class);
    } */

     public function setLogoAttribute($value)
    {
        $attribute_name = "logo";
        $disk = "public";
        $destination_path = "uploads/restaurants";

        $this->uploadFileToDisk($value, $attribute_name, $disk, $destination_path);
    }


     /*
    |--------------------------------------------------------------------------
    | Methods for storing uploaded files (used in CRUD).
    |--------------------------------------------------------------------------
    */

    /**
     * Handle file upload and DB storage for a file:
     * - on CREATE
     *     - stores the file at the destination path
     *     - generates a name
     *     - stores the full path in the DB;
     * - on UPDATE
     *     - if the value is null, deletes the file and sets null in the DB
     *     - if the value is different, stores the different file and updates DB value.
     *
     * @param  [type] $value            Value for that column sent from the input.
     * @param  [type] $attribute_name   Model attribute name (and column in the db).
     * @param  [type] $disk             Filesystem disk used to store files.
     * @param  [type] $destination_path Path in disk where to store the files.
     */
    public function uploadFileToDisk($value, $attribute_name, $disk, $destination_path)
    {
        $request = \Request::instance();

        // if a new file is uploaded, delete the file from the disk
        if ($request->hasFile($attribute_name) &&
            $this->{$attribute_name} &&
            $this->{$attribute_name} != null) {
            \Storage::disk($disk)->delete($this->{$attribute_name});
            $this->attributes[$attribute_name] = null;
        }

        // if the file input is empty, delete the file from the disk
        if (is_null($value) && $this->{$attribute_name} != null) {
            \Storage::disk($disk)->delete($this->{$attribute_name});
            $this->attributes[$attribute_name] = null;
        }

        // if a new file is uploaded, store it on disk and its filename in the database
        if ($request->hasFile($attribute_name) && $request->file($attribute_name)->isValid()) {
            // 1. Generate a new file name
            $file = $request->file($attribute_name);
            $new_file_name = md5($file->getClientOriginalName().time()).'.'.$file->getClientOriginalExtension();

            // 2. Move the new file to the correct path
            $file_path = $file->storeAs($destination_path, $new_file_name, $disk);

            // 3. Save the complete path to the database
            $this->attributes[$attribute_name] = 'storage/' . $file_path;
        }
    }



/**
 * @param $query
 * @param $lat
 * @param $lng
 * @param $radius numeric
 * @param $units string|['K', 'M']
 */
public function scopeNearLatLng($query, $lat, $lng, $radius = 2, $units = 'M')
{
    $distanceUnit = $this->distanceUnit($units);

    if (!(is_numeric($lat) && $lat >= -90 && $lat <= 90)) {
        throw new Exception("Latitude must be between -90 and 90 degrees.");
    }

    if (!(is_numeric($lng) && $lng >= -180 && $lng <= 180)) {
        throw new Exception("Longitude must be between -180 and 180 degrees.");
    }

    $haversine = sprintf('*, (%f * DEGREES(ACOS(COS(RADIANS(%f)) * COS(RADIANS(latitude)) * COS(RADIANS(%f - longitude)) + SIN(RADIANS(%f)) * SIN(RADIANS(latitude))))) AS distance',
        $distanceUnit,
        $lat,
        $lng,
        $lat
    );

    $subselect = clone $query;
    $subselect
        ->selectRaw(DB::raw($haversine));

    // Optimize the query, see details here:
    // http://www.plumislandmedia.net/mysql/haversine-mysql-nearest-loc/

    $latDistance      = $radius / $distanceUnit;
    $latNorthBoundary = $lat - $latDistance;
    $latSouthBoundary = $lat + $latDistance;
    $subselect->whereRaw(sprintf("latitude BETWEEN %f AND %f", $latNorthBoundary, $latSouthBoundary));

    $lngDistance     = $radius / ($distanceUnit * cos(deg2rad($lat)));
    $lngEastBoundary = $lng - $lngDistance;
    $lngWestBoundary = $lng + $lngDistance;
    $subselect->whereRaw(sprintf("longitude BETWEEN %f AND %f", $lngEastBoundary, $lngWestBoundary));

    $query
        ->from(DB::raw('(' . $subselect->toSql() . ') as d'))
        ->where('distance', '<=', $radius);
}

/**
 * @param $units
 */
private function distanceUnit($units = 'K')
{
    if ($units == 'K') {
        return static::DISTANCE_UNIT_KILOMETERS;
    } elseif ($units == 'M') {
        return static::DISTANCE_UNIT_MILES;
    } else {
        throw new Exception("Unknown distance unit measure '$units'.");
    }
}

}

app/Http/Controllers/Api/RestaurantsController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RestaurantsController extends Controller
{

}

app/Http/Controllers/RestaurantsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Restaurant;
use App\Models\OfferBanner;
use Illuminate\Http\Request;

class RestaurantsController extends Controller
{
    public function index()
    {
        if(!session()->has('lat') || !session()->has('lng') || !session()->has('address'))
        {
            return redirect('/');
        }

        $restaurants = Restaurant::latest();

        $restaurants = $restaurants->NearLatLng(session('lat'), session('lng'), config('settings.restaurants_radius', 2))
            ->orderBy('distance', 'ASC');

        if(request()->has('filter'))
        {
            if(request('filter') == 'veg')
            {
                $restaurants->where('is_pure_veg', 1);
            } else if(request('filter') == 'nonveg')
            {
                $restaurants->where('is_pure_veg', 0);
            } else if(request('filter') == 'popular')
            {
                $restaurants->where('is_featured', 1);
            }  else if(request('filter') == 'budget')
            {
                $restaurants->where('cost_for_two', '<', 500);
            }
        }



        $restaurants = $restaurants->paginate(9);

        $offers = OfferBanner::all();

        if(!count($restaurants))
        {
            return view('restaurants.none');
        }

        return view('restaurants.index', compact('restaurants', 'offers'));
    }

    public function show($city, $restaurantSlug)
    {

       // dd(\Cart::getContent());
        $restaurant = Restaurant::where('slug', $restaurantSlug)->first();




        $allitems = $restaurant->items()->where('is_featured', 0);
        $featuredItems = $restaurant->featuredItems();

        if(request()->has('veg') && request('veg') == 1 )
        {
             $allitems = $allitems->where('is_veg', 1);
             $featuredItems = $featuredItems->where('is_veg', 1);
        }
        $searchitems = [];
        if(request()->has('query') && request()->has('query') != '')
        {
                $searchitems = $restaurant->items()->where('name', 'like', '%' . request('query') . '%')->get()->groupBy('cuisine_id');
        }

        $allitems = $allitems->get()->groupBy('cuisine_id');
        $featuredItems = $featuredItems->get();


        return view('restaurants.show', compact('restaurant', 'allitems', 'featuredItems', 'searchitems'));

    }
}

resources/views/restaurants/partials/_card.blade.php
<a href="/restaurants/{{ str_slug($restaurant->city->name) }}/{{$restaurant->slug}}" class="card restaurant-card mb-3">
  <img class="card-img-top" src="{{ isset($restaurant->logo) ? url($restaurant->logo) : 'http://via.placeholder.com/100x100' }}" style="height: 180px;" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">
      @if($restaurant->is_pure_veg)
      <img src="/img/veg.png" style="width: 15px;height: 15px;margin-top: -4.5px;
      margin-right: 5px;" alt="restaurant">@endif
      {{ $restaurant->name }}</h5>
    <p class="card-text">{{ $restaurant->cuisines_available }} <br><span class="open-indicator badge badge-{{ $restaurant->open_indicator }}">{{ $restaurant->open_status }}</span> </p>

    <div class="d-flex justify-content-between info">
        <span class="badge badge-success rating"><i class="fas fa-star"></i> 3.5 </span>
        <span>|</span>
        <span class="delivery_time"> {{ $restaurant->distance < 3 ? '45 MINS' : '60 MINS' }} </span>
        <span>|</span>
        <span class="for_two"> &#8377; {{ $restaurant->cost_for_two }} FOR TWO</span>
    </div>



     @if($restaurant->promo_text != '' || $restaurant->promo_text != null)
    @if(checkRange($restaurant->valid_from, $restaurant->valid_through, date('Y-m-d')))
    <hr class="offer-hr">
      <div class="offer">
         {{ $restaurant->promo_text }}
      </div>
     @endif
   @endif
  </div>
</a>

resources/views/restaurants/partials/_customs.blade.php
<div class="modal" id="toppings-{{$item->id}}" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><b>Customise '{{ $item->name }}'</b> <br> <small class="text-muted">&#8377; {{ $item->special_price }}</small></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <customise-item @updated="updateCart" :item="{{ $item }}"></customise-item>
      </div>
    </div>
  </div>
</div>

resources/views/restaurants/partials/_filters.blade.php
 <div class="list-group restaurant-filters">
  <a href="/restaurants/explore" class="list-group-item list-group-item-action {{ is_filter_active('all') }}"><i class="far fa-list-alt mr-2"></i> All Restaurants</a>
  <a href="/restaurants/explore?filter=popular" class="list-group-item list-group-item-action {{ is_filter_active('popular') }}"><i class="fas fa-star mr-2"></i> Most Popular</a>
  <a href="/restaurants/explore?filter=budget" class="list-group-item list-group-item-action {{ is_filter_active('budget') }}"><i class="fas fa-money-bill-wave mr-2"></i> Pocket Friendly</a>
  <a href="/restaurants/explore?filter=veg" class="list-group-item list-group-item-action {{ is_filter_active('veg') }}"><i class="fas fa-feather-alt mr-2"></i> Pure Veg</a>
  <a href="/restaurants/explore?filter=nonveg" class="list-group-item list-group-item-action {{ is_filter_active('nonveg') }}"><i class="fas fa-fish mr-2"></i> Non Veg Special</a>
</div>

resources/views/restaurants/partials/_itemCard.blade.php
<div class="card item-card">
  <img class="card-img-top" src="{{ isset($item->photo) ? url($item->photo) : 'http://via.placeholder.com/350x250' }}" style="max-height: 200px;height: 200px;" alt="restaurants item">
  <div class="card-body">
    <h5 class="card-title">@if($item->is_veg)
             <img class="veg-indicator" src="/img/veg.png" style="width: 15px;height: 15px;margin-top: -4.5px;" alt="veg restaurants">
            @else
            <img class="veg-indicator" src="/img/nonveg.png" style="width: 15px;height: 15px;margin-top:-4.5px;" alt="nonveg restaurants">
            @endif
           {{ substr($item->name, 0, 25) }}</h5>
    <p class="card-text">{{ $item->cuisine->name }}</p>
    <div class="d-flex justify-content-between">
          <span class="price">{!! getPriceView($item) !!}</span>

       @if($restaurant->is_open)
       @if($item->isCustomisable())
            <a href="#toppings-{{$item->id}}"  id="add-cart-{{$item->id}}" data-toggle="modal" class="btn btn-outline-success btn-sm add-item">Add</a>
         @else
         <input type="number" data-key="{{ isInCart($item) ? getCartItem($item)->id : 0 }}" style="display: {{ isInCart($item) ? 'inline-block' : 'none' }}" class="number-input" value="{{ isInCart($item) ? getCartItem($item)->quantity : 0 }}" id="{{ $item->id }}-menu-qty" @change="updateCartItemFromMenu('{{ $item->id }}')" >
        <a href="javascript:;" style="display: {{ !isInCart($item) ? 'inline-block' : 'none' }}" @click.prevent="addToCart({{$item}})" id="add-cart-{{$item->id}}" class="btn btn-outline-success btn-sm add-item">Add</a>
        @endif
        @endif

    </div>

  </div>

</div>


 @if($item->isCustomisable())
  @include('restaurants.partials._customs')
  @endif

resources/views/restaurants/partials/_itemFilters.blade.php
 <div class="list-group cuisine-filters">
   {{--  @foreach($restaurant->cusineMenu as $cuisine)
        <a href="/restaurants/explore" class="list-group-item list-group-item-action {{ is_filter_active('all') }}">All Restaurants</a>
    @endforeach --}}

     <ul class="nav flex-column flex-nowrap">
                @if(request()->has('query') && request('query') != '')
                    <li class="nav-item"><a class="nav-link head" href="#search-items">Search Results</a></li>
                @endif
                @if(count($featuredItems))
                    <li class="nav-item"><a class="nav-link head" href="#featured"><i class="fa fa-check-circle d-none"></i> Featured Items</a></li>
                @endif
                @foreach($restaurant->cuisineMenu as $cuisine)
                @if($cuisine->parent_id == 0 || $cuisine->parent_id == null)
                     @if($cuisine->subs()->count() == 0)
                        <li class="nav-item"><a class="nav-link" href="#cuisine-{{$cuisine->id}}"><i class="fa fa-check-circle d-none"></i> {{ $cuisine->name }}</a></li>
                     @else
                            <li class="nav-item">
                                <a class="nav-link sub collapsed" href="#submenu-{{$cuisine->id}}" data-toggle="collapse" data-target="#submenu-{{$cuisine->id}}">{{ $cuisine->name }}</a>
                                <div class="collapse" id="submenu-{{$cuisine->id}}" aria-expanded="false">
                                                    <ul class="flex-column nav pl-4">
                                                        @foreach($cuisine->subs as $subCuisine)
                                                            @if($subCuisine->items()->where('restaurant_id', $restaurant->id)->count())
                                                                <li class="nav-item">
                                                                    <a class="nav-link p-1" href="#cuisine-{{$subCuisine->id}}">
                                                                        <i class="fa fa-check-circle d-none"></i> {{ $subCuisine->name }}
                                                                    </a>
                                                                </li>
                                                            @endif
                                                        @endforeach

                                                    </ul>
                                                </div>

                                  </li>
                            @endif
                            @endif
                            @endforeach


            </ul>
</div>

resources/views/restaurants/partials/_itemList.blade.php
<div class="menu-item d-flex justify-content-between align-items-center {{ $item->is_veg ? '' : 'item-non-veg' }}">
    <div style="flex: 1">
        <h4 class="name">@if($item->is_veg)
                 <img class="veg-indicator" src="/img/veg.png" style="width: 15px;height: 15px;margin-top: -4.5px;" alt="veg restaurants">
                @else
                <img class="veg-indicator" src="/img/nonveg.png" style="width: 15px;height: 15px;margin-top:-4.5px;" alt="nonveg restaurants">
                @endif
               {{ substr($item->name, 0, 25) }}</h4>
        <p class="price">{!! getPriceView($item) !!}</p>
    </div>


         @if($restaurant->is_open)
         @if($item->isCustomisable())
            <a href="#toppings-{{$item->id}}"  id="add-cart-{{$item->id}}" data-toggle="modal" class="btn btn-outline-success btn-sm add-item">Add</a>
         @else
         <input type="number" data-key="{{ isInCart($item) ? getCartItem($item)->id : 0 }}" style="display: {{ isInCart($item) ? 'inline-block' : 'none' }}" class="number-input" value="{{ isInCart($item) ? getCartItem($item)->quantity : 0 }}" id="{{ $item->id }}-menu-qty" @change="updateCartItemFromMenu('{{ $item->id }}')" >
        <a href="javascript:;" style="display: {{ !isInCart($item) ? 'inline-block' : 'none' }}" @click.prevent="addToCart({{$item}})" id="add-cart-{{$item->id}}" class="btn btn-outline-success btn-sm add-item">Add</a>
        @endif
        @endif
</div>


 @if($item->isCustomisable())
    @include('restaurants.partials._customs')
@endif