routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('/reset', function(){
    session()->flush();

    return redirect('/');
});

Auth::routes();

Route::post('/password/phone', 'Auth\ForgotPasswordController@phone')->name('password.phone');
Route::get('/password/change', 'Auth\ResetPasswordController@change')->name('password.change');
Route::post('/password/update', 'Auth\ResetPasswordController@update')->name('password.update');

Route::get('/register/success', 'Auth\RegisterController@success');

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/restaurants/request', 'RestaurantRequestController@store');
Route::post('/restaurants/request/bulk', 'RestaurantRequestController@bulk');
Route::get('/restaurants/explore', 'RestaurantsController@index');
Route::get('/restaurants/{city}/{restaurantSlug}', 'RestaurantsController@show');

Route::post('/cart/add', 'CartController@store');
Route::post('/cart/custom/add', 'CartController@storeCustom');
Route::post('/cart/remove/{itemId}', 'CartController@destroy');
Route::post('/cart/update/{itemId}', 'CartController@update');
Route::get('/cart', 'CartController@index');

Route::get('/search', 'SearchController@index');

Route::get('/checkout', 'CheckoutController@index');

Route::post('/orders', 'OrdersController@store');
Route::get('/orders/{order}', 'OrdersController@show');
Route::get('/orders/{order}/invoice', 'OrdersController@invoice');
Route::get('/orders/{order}/confirm', 'OrdersController@confirm');
Route::get('/orders/{order}/ready', 'OrdersController@ready');
Route::get('/orders/{order}/picked', 'OrdersController@picked');
Route::get('/orders/{order}/delivered', 'OrdersController@delivered');
Route::get('/orders/{order}/cancel', 'OrdersController@cancel');
Route::get('/thankyou', 'ThankyouController@index');
Route::get('/pay', 'PaymentsController@pay');

Route::post('/payments/response/', 'PaymentsController@response');
Route::post('/payments/cancel/', 'PaymentsController@cancel');

Route::post('/addresses', 'AddressController@store');
Route::get('/addresses/{address}/delete', 'AddressController@destroy');
Route::post('/addresses/{address}/update', 'AddressController@update');

Route::post('user/location', 'Api\UserLocationController@store');

Route::get('/my-account', 'AccountController@profile');
Route::get('/my-account/orders', 'AccountController@orders');
Route::get('/my-account/offers', 'AccountController@offers');
Route::get('/my-account/payments', 'AccountController@payments');
Route::get('/my-account/bookmarks', 'AccountController@bookmarks');
Route::get('/my-account/addresses', 'AccountController@addresses');

Route::post('/account/update', 'AccountController@updateProfile');
Route::post('/account/update/password', 'AccountController@updatePassword');
Route::post('/account/phone/update', 'AccountController@updatePhone');

Route::get('/bookmarks/{restaurant}', 'BookmarkController@store');
Route::get('/bookmarks/{restaurant}/remove', 'BookmarkController@destroy');

Route::get('/coupons', 'CouponsController@index');
Route::post('/coupons/apply', 'CouponsController@apply');
Route::get('/coupons/remove', 'CouponsController@destroy');
Route::post('/coupons/apply/foodoor', 'CouponsController@applyFoodoor');

Route::post('/cart/clear', 'CartController@clear');


Route::get('/company/about', 'CompanyController@about');
Route::get('/company/contact', 'CompanyController@contact');
Route::get('/company/careers', 'CompanyController@careers');
Route::get('/company/team', 'CompanyController@team');
Route::get('/company/terms', 'CompanyController@terms');
Route::get('/company/privacy-policy', 'CompanyController@privacy');

Route::post('/contact', 'ContactController@store');

app/Models/Order.php
<?php

namespace App\Models;

use App\User;
use Backpack\CRUD\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'orders';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $guarded = [];
    // protected $hidden = [];
    // protected $dates = [];

   public function restaurant()
   {
        return $this->belongsTo(Restaurant::class);
   }

    public function customer()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getBookingDateAttribute()
    {
        return $this->created_at->format('d/m/Y');
    }

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function getStatusTextAttribute()
    {
        $statuses = ['Order Placed', 'Confirmed by Restaurant', 'Order Ready' , 'Order Picked', 'Order Delivered'];
        return $statuses[$this->status];
    }

    public function getCancelledByNameAttribute()
    {
        return $this->cancelled_by == 0 ? 'Customer' : 'Restaurant';
    }

    public function getItemsCountAttribute()
    {
        return count($this->items);
    }

    public function getPaymentBadgeAttribute()
    {
        if($this->payment_mode == 0)
        {
            if($this->status < 4) {
                $status = 'Payment Pending';
                $color = 'danger';
            } else {
                $status = 'Payment Received';
                $color = 'success';
            }
        } else {
            if($this->status > -1) {
               $status = 'Payment Received';
                $color = 'success';
            }
        }

        return '<small><span class="badge badge-' . $color . '">' . $status . '</span></small>';
    }

    public function getStatusBadgeAttribute()
    {
        $statuses = ['Awaiting Confirmation', 'Confirmed', 'Ready', 'Picked', 'Delivered'];
        $colors = ['secondary', 'primary', 'info', 'warning', 'success'];
        return '<small><span class="badge badge-' . $colors[$this->status] . '">' . $statuses[$this->status] . '</span></small>';
    }
    public function getAmountEarnedAttribute()
    {
        return $this->subtotal - $this->commission_earned;
    }

    public function confirmOrder($crud = false)
    {
        if($this->status < 1)
        {
           return '<a class="btn btn-xs btn-success" href="/orders/'. $this->id . '/confirm" data-toggle="tooltip" title="Confirm Order"><i class="fa fa-check"></i> Confirm Order</a>';
        } elseif($this->status == 1) {

                 return '<a class="btn btn-xs btn-info" href="/orders/'. $this->id . '/ready" data-toggle="tooltip" title="Order Ready" ><i class="fa fa-check"></i> Order Ready</a>';
        } elseif($this->status == 2) {

                 return '<a class="btn btn-xs btn-info" href="/orders/'. $this->id . '/picked" data-toggle="tooltip" title="Order Picked" ><i class="fa fa-check"></i> Order Picked</a>';
        } elseif($this->status == 3) {

                 return '<a class="btn btn-xs btn-success" href="/orders/'. $this->id . '/delivered" data-toggle="tooltip" title="Order Delivered" ><i class="fa fa-check"></i> Order Delivered</a>';
        } else {
             return '<a class="btn btn-xs btn-success" href="#" data-toggle="tooltip" title="Order Delivered" disabled><i class="fa fa-check"></i> Order Closed</a>';
        }

    }

     public function cancelOrder($crud = false)
    {
           return
           '<a class="btn btn-xs btn-danger" href="/orders/'. $this->id . '/cancel" data-toggle="tooltip"  title="Cancel Order"><i class="fa fa-file-text"></i> Cancel</a>';
    }


    public function invoice($crud = false)
    {
           return
           '<a class="btn btn-xs btn-primary" href="/orders/'. $this->id . '/invoice" data-toggle="tooltip" target="_blank" title="Download Invoice"><i class="fa fa-file-text"></i> Invoice</a>';
    }




    public function addCustomerDetails($addressId)
    {
        $address = Address::findOrFail($addressId);
        $this->user_id = auth()->id();
        $this->customer_name = auth()->user()->name;
        $this->customer_phone = auth()->user()->phone;
        $this->customer_email = auth()->user()->email;
        $this->delivery_location = $address->location;
        $this->delivery_latitude = $address->latitude;
        $this->delivery_longitude = $address->longitude;
        $this->delivery_door_no = $address->door_no;
        $this->delivery_road_name = $address->road_name;
        $this->delivery_landmark = $address->landmark;
    }

    public function addRestaurantDetails($restaurant)
    {

        $this->restaurant_id = $restaurant->id;
        $this->restaurant_name = $restaurant->name;
        $this->restaurant_location = $restaurant->location;
        $this->restaurant_latitude = $restaurant->latitude;
        $this->restaurant_longitude = $restaurant->longitude;
        $this->restaurant_area = $restaurant->area;
    }

    public function addBillingDetails($bill)
    {
        $this->subtotal = $bill['subTotal'];
        $this->tax = $bill['gst'];
        $this->delivery_charges = $bill['deliveryCharges'];
        $this->total = ceil(round($bill['total'], 2));
        $this->discount = $bill['discount'] != null ? $bill['discount']  : 0;
        $this->commission_earned = $this->subtotal * ($this->restaurant->commission/100);
    }

    public function storeItems($items)
    {
        foreach ($items as $key => $item) {
            $this->items()->create(['menu_item_id' => $item->attributes->item_id, 'name' => $item->name,
                                'price' => $item->price, 'qty' => $item->quantity, 'total' => $item->price * $item->quantity,
                                'customs' => getCustomsString($item)]);
        }
    }


    public function getStatusIconAttribute()
    {
         $statuses = ['Awaiting Confirmation', 'Confirmed', 'Ready', 'Picked', 'Delivered'];
         $icons = ['clock', 'check-circle', 'shopping-bag', 'motorcycle', 'check'];
         return $icons[$this->status];
    }

    public function getStatusDescAttribute()
    {
        $statuses = ['Awaiting Confirmation', 'Confirmed', 'Ready', 'Picked', 'Delivered'];
        $colors = ['secondary', 'primary', 'info', 'warning', 'success'];
        return $statuses[$this->status];
    }
}

app/Http/Controllers/Api/OrdersController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrdersController extends Controller
{
    //
}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Order;
use App\Models\MenuItem;
use Illuminate\Http\Request;
use App\Events\OrderStatusChanged;

class OrdersController extends Controller
{
    public function store()
    {
        $items = \Cart::getContent();

        if(count($items))
        {
            $menuItem = MenuItem::findOrFail($items->first()->attributes->item_id);
            $restaurant = $menuItem->restaurant;
            $order = new Order;

            $order->addCustomerDetails(request('address_id'));

            $order->addRestaurantDetails($restaurant);

            $order->delivery_alt_no = request('delivery_alt_no');

            $bill['subTotal'] = \Cart::getSubTotal();
            $bill['gst'] = round($bill['subTotal'] * (5/100), 2);
            $bill['deliveryCharges'] = 30;
            $condition = \Cart::getCondition('discount');
            if(isset($condition))
            {
              $bill['discount'] = $condition->getCalculatedValue(\Cart::getTotal());
            } else {
                 $bill['discount'] = null;
            }
            $bill['total'] = \Cart::getTotal() + $bill['gst'] + $bill['deliveryCharges'];

            $order->addBillingDetails($bill);

            $order->payment_mode = request('payment_mode');

            $order->suggestions = request('suggestions');

            $order->save();

            $order->storeItems($items);

            if($order->payment_mode == 0)
            {
                \Cart::clear();
                 \Cart::clearCartConditions();
                 $message = 'Thanks for ordering with Pots. Your order no: '. $order->id . ' and bill amount : Rs. '. $order->total .'/- . We are waiting for restaurant confirmation and will update you soon.';
                 $response = sendSMS($order->customer_phone, $message);
                 $messageToRest = 'You have received a new order of Rs. '. $order->total .'/-. Order Invoice : https://foodoor.in/orders/'. $order->id  .'/invoice';
                 sendSMS($order->restaurant->contact_phone, $messageToRest);
                 return response(['redirect' => '/thankyou?order=' . $order->id], 200);

            } else {
               $order->update(['status' => -2]);
               return response(['redirect' => '/pay?order=' . $order->id], 200);
            }

        } else {
            return response(['error' => 'Empty cart'], 500);
        }
    }

    public function invoice(Order $order)
    {
        $invoice = \PDF::loadView('orders.invoice', compact('order'));

        return $invoice->download('invoice.pdf');
    }

    public function show(Order $order)
    {
        return view('orders.show', compact('order'));
    }

     public function confirm(Order $order)
    {
        $order->status = 1;
        $order->save();

         event(new OrderStatusChanged($order));

        return back();
    }

     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function ready(Order $order)
    {
        $order->status = 2;
        $order->save();

         event(new OrderStatusChanged($order));

        return back();
    }


     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function picked(Order $order)
    {
        $order->status = 3;
        $order->save();

         event(new OrderStatusChanged($order));

        return back();
    }


     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delivered(Order $order)
    {
        $order->status = 4;
        $order->save();

         event(new OrderStatusChanged($order));


        return back();
    }

     /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function cancel(Order $order)
    {
        $order->status = -1;
        $order->save();

         event(new OrderStatusChanged($order));


        return back();
    }

}

resources/views/orders/invoice.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Pots-order-{{$order->id}}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <style type="text/css">
        html body {
            font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,Sans-serif;
            background: white;
            width: 100%;
            max-width: 800px;
            min-height: 958px;
            margin: 30px auto 30px auto;
        }

        .logo img {
            width: 155px;
            height: auto;
            float: right;
        }
    </style>
</head>
<body>

     <div>

        <div class="logo">
            <img src="https://foodoor.in/img/pots-logo.png" />
            <!-- <img src="https://foodoor.in/img/wordmark.png" /> -->
        </div>

        <div class="mt-2">

            <h3 style="font-weight: bold;">Order no. : #{{$order->id}}

                @if($order->payment_status)
                <span style="font-size: 14px;color: green;"> PAID</span>
                @else
                <span style="font-size: 14px;color: red;" >PAYMENT PENDING</span>
                @endif
            </h3>
            <p>Thanks for choosing Pots, {{$order->customer_name}}! </p>

            <hr>

            <div style="font-size: 15px;">
                <div >
                    <p>Delivery Details : </p>

                    <p><b>{{ $order->customer_name }}</b> | {{ $order->customer_phone }}{{ $order->delivery_alt_no != null && $order->delivery_alt_no != '' ? ', ' . $order->delivery_alt_no : '' }}<br>
                          {{  $order->delivery_location }}<br><b>Door No.: </b> {{ $order->delivery_door_no }} | {{ $order->delivery_road_name }}
                    <br><b>Landmark : </b> {{ $order->delivery_landmark }}</p>

                </div>

                <div >
                    <p>Ordered From : </p>

                    <p><b>{{ $order->restaurant_name }}</b><br>
                          {{ $order->restaurant_area }}
                          </p>
                </div>

                <div >
                    <p>Customer Suggestions : </p>
                    <p>{{$order->suggestions}}</p>
                </div>
            </div>


            <div class="mt-2">
                <table class="table ">

                   <thead class="thead-dark">
                    <tr>
                        <th>Item Name</th>
                        <th>Quantity</th>
                        <th style="text-align: right;">Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($order->items as $item)
                                    <tr>
                                        <td style="font-size: 14px;"> {{ $item->name }}
                                                <br> {{$item->customs}}

                                                </td>
                                        <td style="font-size: 14px;">{{ $item->qty }} x {{ $item->price }}</td>
                                        <td style="font-size: 14px;text-align: right;">Rs. {{ $item->total }}</td>
                                    </tr>
                    @endforeach

                                <tr style="font-size: 14px;text-align: right;">
                                                         <td></td>
                                                        <td style="font-size: 14px;">Subtotal</td>

                                                        <td style="font-size: 14px;">Rs. {{$order->subtotal }}</td>
                                                    </tr>
                                                    @if($order->foodoor_cash > 0)
                                                    <tr style="text-align: right;">
                                                        <td style="font-size: 14px;"></td>
                                                        <td style="font-size: 14px;">Pots Cash</td>

                                                        <td style="font-size: 14px;">-Rs. {{ $order->foodoor_cash }}</td>
                                                    </tr>
                                                    @endif
                                                    <tr style="text-align: right;">
                                                        <td style="font-size: 14px;"></td>
                                                        <td style="font-size: 14px;">GST</td>

                                                        <td style="font-size: 14px;">Rs. {{ $order->tax }}</td>
                                                    </tr>
                                                    <tr style="text-align: right;">
                                                     <td></td>
                                                        <td style="font-size: 14px;">Delivery Charges</td>

                                                        <td style="font-size: 14px;">Rs. {{ $order->delivery_charges}}</td>
                                                    </tr>
                                                    @if($order->discount >0 )
                                                     <tr style="text-align: right;">
                                                     <td></td>
                                                        <td style="font-size: 14px;">Discount</td>

                                                        <td style="font-size: 14px;">- Rs. {{ $order->discount}}</td>
                                                    </tr>
                                                    @endif



                                                    <tr style="text-align: right;">
                                                      <td></td>
                                                        <td style="font-size: 14px;" class="text-color"><strong>Total</strong></td>

                                                             <td style="font-size: 14px;" class="text-color"><strong>Rs. {{ $order->total }}</strong></td>

                                                    </tr>
                                </tbody>
                </table>
            </div>
        </div>


     </div>

</body>
</html>

resources/views/orders/show.blade.php
@extends('layouts.app')
 
@section('title', 'Order | Pots - Food at your door step')

@section('content')

    <div class="bg-light checkout" style="min-height: 90vh;">
        <div class="container py-5 py-res-0">

        <div class="row">

         <div class="col-md-8">
        <div class="card card-shadow">

            <div class="card-body delivery-details">
               <div>
        <h3 class="font-weight-bold mb-3 float-left order-id"><a href="/my-account/orders"><i class="fas fa-arrow-left"></i></a> Order #{{$order->id}} {!! $order->payment_badge !!}</h3>
        @if($order->status >= 4)
        <a class="btn btn-success float-right download-invoice" target="_blank" href="/orders/{{ $order->id }}/invoice">Download Invoice</a>
        @endif
        </div>
         <div class="clearfix"></div>

                       <div class="clearfix"></div>
                <div class="restaurant-details" style="font-size: 18px;">


                     <div class="d-flex mt-2">
                            <div class="d-flex">
                               <i class="fas fa-map-marker-alt location-marker" style="display: none;"></i>
                               <div>
                                <h5 class="restaurant-name mb-0 mt-1">{{ $order->restaurant_name }}</h5>
                                <p class="restaurant-area text-muted">{{  $order->restaurant_area }}</p>
                               </div>
                            </div>
                        </div>

                </div>
                <div class="customer-details mt-3" style="font-size: 18px;">

                     <div class="mt-4 d-flex" style="position: relative;">
                               <i class="fas fa-map-marker-alt location-marker dashed" style="display: none;"></i>
                               <div>
                    <h5 class="customer-name">{{ $order->customer_name }} | {{ $order->customer_phone }}
                      {{ $order->delivery_alt_no != null && $order->delivery_alt_no != '' ? ', ' . $order->delivery_alt_no : ''  }}</h5>

                      <div class="address-box text-muted">
                                    <h6 class="mt-1">{{ str_limit($order->delivery_location, 70) }}</h6>
                                </div>
                              </div>
                    </div>
                </div>
                <div class="order-status-desc" >
                  <i class="fas fa-{{$order->status_icon}}"></i> {{ $order->status_desc }}
                </div>


            </div>


        </div>
      </div>
      <div class="col-md-4">
         <div class="card cart cart-order  card-shadow">
                        <div class="card-body">



                        <a  href="#cartModal" data-toggle="modal" class="view-cart" style="display: none;">Click to view details</a>

                        <div class="cart-items my-3">
                            <div class="">
                              @foreach($order->items as $item)
                            <div  class="item d-flex justify-content-between align-items-center">

                                    <div style="flex: 1">
                                        <h4 class="name">
                                                @if($item->is_veg)
                                                 <img  class="veg-indicator" src="/img/veg.png" style="width: 15px;height: 15px;margin-top: -4.5px;" alt="veg restaurant">
                                                 @else
                                                <img v-else class="veg-indicator" src="/img/nonveg.png" style="width: 15px;height: 15px;margin-top:-4.5px;" alt="nonveg restaurant">
                                                @endif
                                               {{ $item->name }}</h4>
                                        <p class="price" style="font-size: 10px;">{{ $item->customs }}</p>
                                    </div>

                                    <p>₹ {{ $item->price * $item->quantity }}</p>
                                    <!-- <spinner inline controls size="small" :value="item.quantity" @change="(newValue, oldValue, item) => {}"></spinner> -->


                            </div>
                            @endforeach
                            </div>
                        </div>
                        @if($order->discount > 0)
                        <div class="coupons-button">
                            <button v-else class="btn btn-success"><i class="fas fa-check-circle"></i> Coupon Applied</button>
                        </div>
                        @endif
                         <div class="suggestions">
                            <p class="text-muted">{{ $order->suggestions }}</p>
                        </div>
                        <div class="cart-bill">
                            <table class="table table-borderless">
                                 <tbody>
                                    <tr>
                                      <td>Subtotal</td>
                                      <td class="amount">₹ {{ $order->subtotal }}</td>
                                    </tr>
                                    <tr>
                                      <td>GST</td>
                                      <td class="amount">₹ {{ $order->tax }}</td>
                                    </tr>
                                    <tr class="delivery">
                                      <td>Delivery Charges</td>
                                      <td class="amount">₹ {{ $order->delivery_charges }}</td>
                                    </tr>
                                    @if($order->discount > 0)
                                     <tr class="discount">
                                      <td>Discount</td>
                                      <td class="amount">- ₹ {{ $order->discount }}</td>
                                    </tr>
                                    @endif
                                     <tr class="total">
                                      <td>Total</td>
                                      <td class="amount">₹ {{ $order->total }}</td>
                                    </tr>
                                 </tbody>
                            </table>
                        </div>
                       </div>

                    </div>
       </div>
      </div>
        </div>
    </div>


     <div class="modal fade" id="cartModal" style="z-index: 10000000000;" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Purchased Items <br> <small class="count text-muted">{{ count($order->items) }} ITEMS</small></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="padding: 15px !important;padding-right: 22px !important">
        <div class="cart">



                        <div>
                        <div  class="cart-items my-3">
                            <div class="">
                            @foreach($order->items as $item)
                            <div  class="item d-flex justify-content-between align-items-center">

                                    <div style="flex: 1">
                                        <h4 class="name">
                                                @if($item->is_veg)
                                                 <img  class="veg-indicator" src="/img/veg.png" style="width: 15px;height: 15px;margin-top: -4.5px;" alt="veg restaurant">
                                                 @else
                                                <img v-else class="veg-indicator" src="/img/nonveg.png" style="width: 15px;height: 15px;margin-top:-4.5px;" alt="nonveg restaurant">
                                                @endif
                                               {{ $item->name }}</h4>
                                        <p class="price" style="font-size: 10px;">{{ $item->customs }}</p>
                                    </div>

                                    <p>₹ {{ $item->total }}</p>
                                    <!-- <spinner inline controls size="small" :value="item.quantity" @change="(newValue, oldValue, item) => {}"></spinner> -->


                            </div>
                            @endforeach
                            </div>
                        </div>

                        </div>

                    </div>
      </div>

    </div>
  </div>
</div>
@endsection